

name: Deploy
on:
  push:
    branches: [main, docs_site]

jobs:
  docs:
    name: Generate Website
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

 
      - name: setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Install dependencies
        run: |
          git clone git@github.com:trigaten/Prompt_Systematic_Review.git
          cd Prompt_Systematic_Review
          pip install -r requirements.txt
          pip install .
          cd ..
        
          
      - name: Build
        run: sphinx-build -b dirhtml -v docs/source build
        

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/